# Generated by Django 5.1.4 on 2024-12-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
