# Generated by Django 5.1.4 on 2024-12-20 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='bots.profile'),
        ),
    ]
