# Generated by Django 5.1.4 on 2024-12-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='bots.bot'),
        ),
    ]
