# Generated by Django 5.1.4 on 2024-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_chat_input_tokens_chat_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
