# Generated by Django 5.1.4 on 2024-12-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_useraccount_subscription_level_alter_bot_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
