# Generated by Django 5.1.4 on 2024-12-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_alter_bot_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='simple_editor',
            field=models.BooleanField(default=False),
        ),
    ]
