# Generated by Django 5.1.4 on 2025-01-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_bot_response_length_bot_restrict_adult_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
