# Generated by Django 5.1.4 on 2025-01-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0019_profile_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
