# Generated by Django 5.1.4 on 2025-01-03 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0020_useraccount_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLimitHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_level', models.IntegerField(default=0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit_hits', to='bots.useraccount')),
            ],
        ),
    ]
