# Generated by Django 5.1.4 on 2025-01-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_aimodel_bot_ai_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='model',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
