# Generated by Django 5.1.4 on 2025-01-10 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0024_alter_aimodel_input_token_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.aimodel'),
        ),
    ]
