# Generated by Django 5.1.4 on 2025-01-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0026_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='notification_token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
