# Generated by Django 5.1.4 on 2025-03-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0028_revenuecatwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='supported_input_modalities',
            field=models.JSONField(default=list),
        ),
    ]
