# Generated by Django 5.1.4 on 2025-03-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0029_aimodel_supported_input_modalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
