# Generated by Django 5.1.4 on 2025-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0030_message_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_url',
        ),
        migrations.AddField(
            model_name='message',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
