# Generated by Django 5.1.4 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0032_usagelimithit_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enable_web_search',
            field=models.BooleanField(default=False),
        ),
    ]
