# Generated by Django 5.1.4 on 2025-06-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0032_usagelimithit_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(default='en-US', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='partial_transcriptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('partial', 'PARTIAL'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
