# Generated by Django 6.0.3 on 2026-04-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0033_add_enable_web_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenEmailMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_mappings', to='bots.useraccount')),
                ('teen_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teen_email_mapping', to='bots.profile')),
            ],
            options={
                'unique_together': {('oauth_email', 'parent_account')},
            },
        ),
    ]
