# Generated by Django 6.0.3 on 2026-04-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0033_add_enable_web_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
