# Generated by Django 5.1.4 on 2025-03-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0034_bot_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='app',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.app'),
        ),
    ]
