# Generated by Django 5.1.4 on 2025-03-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0035_aimodel_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='app',
        ),
        migrations.CreateModel(
            name='AppAiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.aimodel')),
                ('app', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.app')),
            ],
        ),
    ]
