# Generated by Django 6.0.3 on 2026-05-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0035_deck_flashcard'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flashcard',
            name='unique_flashcard_order_per_deck',
        ),
    ]
