# Generated by Django 6.0.3 on 2026-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0036_remove_flashcard_unique_flashcard_order_per_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
