# Generated by Django 5.1.4 on 2025-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0036_remove_aimodel_app_appaimodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appaimodel',
            constraint=models.UniqueConstraint(fields=('app', 'ai_model'), name='unique_app_ai_model'),
        ),
    ]
