# Generated by Django 6.0.3 on 2026-07-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0037_bot_color_bot_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id']},
        ),
    ]
