# Generated by Django 5.1.4 on 2025-03-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0037_appaimodel_unique_app_ai_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aimodel',
            name='unique_default_model',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='is_default',
        ),
        migrations.AddField(
            model_name='appaimodel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='appaimodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('app', 'is_default'), name='unique_default_model'),
        ),
    ]
