# Generated by Django 6.0.4 on 2026-08-25 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0038_alter_aimodel_options_alter_device_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['oauth_email'], name='profile_oauth_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('oauth_email__isnull', False), ('deleted_at__isnull', True)), fields=('oauth_email',), name='unique_active_profile_oauth_email'),
        ),
    ]
