# Generated by Django 6.0.4 on 2026-08-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0038_alter_aimodel_options_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notify_digest_only',
            field=models.BooleanField(default=False),
        ),
    ]
