# Generated by Django 6.0.4 on 2026-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0038_alter_aimodel_options_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enable_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='voice_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
