# Generated by Django 6.0.3 on 2026-08-26 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0047_flashcard_due_at_flashcard_ease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='use_profile_memory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='memory_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('covered_through_order', models.PositiveIntegerField(default=0, help_text='Highest message.order already included in summary.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='bots.chat')),
            ],
            options={
                'verbose_name': 'chat summary',
                'verbose_name_plural': 'chat summaries',
            },
        ),
        migrations.CreateModel(
            name='MemoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='E.g. summary_refresh, topic_extract, parent_edit.', max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_events', to='bots.chat')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='bots.profile')),
            ],
            options={
                'verbose_name': 'memory event',
                'verbose_name_plural': 'memory events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', help_text='Model-maintained rolling summary of the student.')),
                ('parent_notes', models.TextField(blank=True, default='', help_text='Parent-authored notes visible to the tutor.')),
                ('goals_json', models.JSONField(blank=True, default=list, help_text='Active learning goals, e.g. [{"id": "...", "text": "...", "status": "active"}].')),
                ('topics_json', models.JSONField(blank=True, default=list, help_text='Per-topic strength, e.g. [{"topic": "fractions", "strength": 0.3, "source": "srs"}].')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_updated_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='bots.profile')),
            ],
            options={
                'verbose_name': 'profile memory',
                'verbose_name_plural': 'profile memories',
            },
        ),
    ]
