# Generated by Django 6.0.4 on 2026-08-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0048_bot_use_profile_memory_useraccount_memory_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_mode',
            field=models.CharField(choices=[('all', 'all'), ('allowlist', 'allowlist')], default='all', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_bots',
            field=models.ManyToManyField(blank=True, related_name='allowed_profiles', to='bots.bot'),
        ),
        migrations.CreateModel(
            name='ProfileSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('windows_json', models.JSONField(blank=True, default=list)),
                ('block_message', models.CharField(default="It's outside your chat hours. Try again later or ask a parent.", max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='bots.profile')),
            ],
        ),
    ]
