# Generated by Django 6.0.3 on 2026-08-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0049_profile_access_mode_profile_allowed_bots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enable_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='intent',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('homework', 'Homework'), ('check_work', 'Check Work')], default='chat', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
