# Generated by Django 6.0.4 on 2026-08-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0050_bot_enable_vision_bot_enable_voice_message_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enable_voice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='voice_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
