# Generated by Django 6.0.3 on 2026-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0054_useraccount_usage_reset_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notify_study_due',
            field=models.BooleanField(default=False),
        ),
    ]
