# Generated by Django 6.0.3 on 2026-09-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0055_message_model_id'),
        ('bots', '0055_device_notify_study_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='usage_reset_version',
            field=models.IntegerField(default=1),
        ),
    ]
