# Generated by Django 6.0.3 on 2026-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0056_useraccount_usage_reset_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='usage_reset_pricing',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
